### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by arjung128** [vpulab/Semantic-Aware-Scene-Recognition#1]
First off, thank you very much for open-sourcing the code for your state-of-the-art results!

Would it be possible to open-source the best performing model you obtained? 

I understand that you have provided some code, but I don't know if enough code/details are provided to train the model from scratch (like there is no train.py, no mention of how much computational power is required, etc.)...

Could one of the two things above be provided please?

**Comment by alexlopezcifuentes** [comment]
We are uploading the last version of the models you requested. Models should be uploaded in a couple of days.

**Comment by alexlopezcifuentes** [comment]
We have just uploaded ResNet-50 models. I close the issue.
