### ISSUE TITLE
Model zoo links expired

### ISSUE THREAD

**Issue by YicongHong** [vpulab/Semantic-Aware-Scene-Recognition#10]
Hello, I am trying to download the models from the model zoo links, but it seems that they have expired. Could you fix that for us please? Thanks a lot.

**Comment by alexlopezcifuentes** [comment]
Hello, thanks for the report, we have been migrating all the download links. Now everything should be fixed.

**Comment by YicongHong** [comment]
Thanks a lot for resolving this issue. But it seems that the network weights for RGB Branch - Places365 is incorrect. Can you please double-check on that? Thanks!

**Comment by alexlopezcifuentes** [comment]
Can you please specify which is exactly the error you are getting. The download link is correct, so it seems like a configuration error. have you checked that you are using ResNet-18?

**Comment by YicongHong** [comment]
I think it is not a configuration error, yes I am using ResNet18, RGB only. 
The network weights doesn't match the model - a full list of "Missing & Unexpected key(s) in state_dict".
I tried with MITIndoor67 weights and they work well. But not for Places365.

**Comment by alexlopezcifuentes** [comment]
I did not see your edit on the issue, I thought you were talking about "Ours" model not the "RGB" one. Indeed there was something wrong with the file, I have updated it again.

Can you please check if you can load it now?

**Comment by YicongHong** [comment]
Hi Alex. I re-tried both the "RGB" and "Ours" and they both work now. Thanks a lot for your help!
