### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by nagyrajmund** [vpulab/Semantic-Aware-Scene-Recognition#19]
Hi,

I just wanted to say thank you for sharing your code and the pretrained weights. It's a super cool work! :)

**Comment by alexlopezcifuentes** [comment]
Hi!
Thank you for the really nice comment, I highly appreciate it! Glad you like the work, do not hesitate to ask any questions related to the code o the paper.

**Comment by nagyrajmund** [comment]
Hi @alexlopezcifuentes, 

Could you tell me what you used to draw the figure of the architecture?

**Comment by alexlopezcifuentes** [comment]
Hi, sorry to disappoint you if you were expecting a fancy application but I just used PowerPoint for the drawings...

**Comment by nagyrajmund** [comment]
Ah, I see. It looks great! :o)
Thanks for the answer.
