### ISSUE TITLE
How to test this model?

### ISSUE THREAD

**Issue by rohanakut** [vpulab/Semantic-Aware-Scene-Recognition#22]
Thank you for the amazing repo
However, it appears as if this repo is used for training the model. is it possible to create a file that just takes the input image and generates an output from the trained model?

**Comment by alexlopezcifuentes** [comment]
Hi!

The repo is precisly for evaluating the model not for training. If you want to extract results for a single image you can create your own script using fragments of the code, however, you can get the same results using batch_size=1
