### ISSUE TITLE
how to test model on new images

### ISSUE THREAD

**Issue by vaibhavkale20009** [vpulab/Semantic-Aware-Scene-Recognition#27]

**Comment by vaibhavkale20009** [comment]
how can i modify code to input a image and get the semantics as output

**Comment by alexlopezcifuentes** [comment]
Hi!

We don't provide a specific Semantic Segmentation code to obtain the semantics, we just provide the semantic segmentations extracted by PSPNet used to obtain the results from the paper.

You can use any Semantic Segmentation CNN of your choice. You just have to save the top3 labels and top3 scores leveraging the 3 channels of an RGB image.

Alex.
