### ISSUE TITLE
Link Down: Cannot downloads Weight files and nois_semantic data

### ISSUE THREAD

**Issue by xshan786** [vpulab/Semantic-Aware-Scene-Recognition#29]
Hello, 

Thank you for your work. 

I want to download and test your work but the download link is not working currently. can you help with this?

Thank you

**Comment by jcsma** [comment]
Dear @Zeeshan313,

we had an unexpected issue with the server and the links shoud now be available. Please check again.

Best regards,
Juan Carlos
