### ISSUE TITLE
noisy_annotations vs noisy_scores

### ISSUE THREAD

**Issue by arjung128** [vpulab/Semantic-Aware-Scene-Recognition#5]
```
|----images
	|--- training
		ADE_train_00000001.jpg
		...
	|--- validation
		ADE_val_00000001.jpg
		...
|----noisy_annotations_RGB
	|--- training
		ADE_train_00000001.png
		...
	|--- validation
		ADE_train_00000001.png
		...
|----noisy_scores_RGB
	|--- training
		ADE_train_00000001.png
		...
	|--- validation
		ADE_train_00000001.png
		...
```

The difference between the `images` folder and the other two folders seems to be `.jpg` vs `.png`. But what's the difference between the `noisy_annotations_RGB` folder and the `noisy_scores_RGB` folder? Or is there a typo?

And the validation folders of the `noisy_annotations_RGB` and `noisy_scores_RGB` folders should not contain train set files, as shown above, right?

**Comment by alexlopezcifuentes** [comment]
Indeed, that was a typo in the validation file names. I have updated the documentation.

The difference between `noisy_annotations_RGB` folder and the `noisy_scores_RGB` folder is the following:

- `noisy_annotations_RGB` folder contains the **semantic labels** for each image. It is a 3-channel image as for each pixel we have 3 semantic labels (the Top3 predicted by the semantic segmentation network).
- `noisy_scores_RGB` folder contains the **semantic scores** for each image. It is a 3-channel image as for each pixel we have 3 semantic scores.

**Comment by piaohe111** [comment]
@arjung128  do you know what the semantic score mean ? and how to get this value?
